Repository Redot-Engine/redot-docs, pull requests merged in 2024-10, with the labels that each got.

#37 Add non-political Encrypting Save Games Doc
  tutorials/io/encrypting_save_games.rst
  tutorials/io/index.rst
Labels: enhancement, area:manual

#39 [stable] Add non-political Encrypting Save Games Doc
  tutorials/io/encrypting_save_games.rst
  tutorials/io/index.rst
Labels: enhancement, area:manual

#40 Remove vestigial encrypting saves trash
  tutorials/io/encrypting_save_games.rst
Labels: bug, area:manual

#38 Fix incorrect Redot migration mappings
  migrate.py
Labels: bug, rebranding

#36 Merge commit godotengine/godot-docs@4895db1
  _tools/redirects/redirects.csv
  contributing/development/compiling/compiling_for_ios.rst
  contributing/development/compiling/compiling_for_macos.rst
  contributing/development/configuring_an_ide/visual_studio_code.rst
  contributing/development/core_and_modules/variant_class.rst
  tutorials/2d/index.rst
  tutorials/3d/index.rst
  tutorials/3d/standard_material_3d.rst
  tutorials/assets_pipeline/escn_exporter/animation.rst
  tutorials/assets_pipeline/escn_exporter/img/armature.jpg
  tutorials/assets_pipeline/escn_exporter/img/body_type.jpg
  tutorials/assets_pipeline/escn_exporter/img/col_only.png
  tutorials/assets_pipeline/escn_exporter/img/collision_shapes.jpg
  tutorials/assets_pipeline/escn_exporter/img/dope_sheet.jpg
  tutorials/assets_pipeline/escn_exporter/img/enable_physics.png
  tutorials/assets_pipeline/escn_exporter/img/external_mat_option.jpg
  tutorials/assets_pipeline/escn_exporter/img/gd_dot_material.jpg
  tutorials/assets_pipeline/escn_exporter/img/hide.jpg
  tutorials/assets_pipeline/escn_exporter/img/in_godot.jpg
  tutorials/assets_pipeline/escn_exporter/img/light_properties.jpg
  tutorials/assets_pipeline/escn_exporter/img/material_search.jpg
  tutorials/assets_pipeline/escn_exporter/img/nla_editor.jpg
  tutorials/assets_pipeline/escn_exporter/img/nla_pushdown.jpg
  tutorials/assets_pipeline/escn_exporter/img/nla_strip.jpg
  tutorials/assets_pipeline/escn_exporter/img/stash_action.jpg
  tutorials/assets_pipeline/escn_exporter/img/stash_action_option.jpg
  tutorials/assets_pipeline/escn_exporter/index.rst
  tutorials/assets_pipeline/escn_exporter/lights.rst
  tutorials/assets_pipeline/escn_exporter/material.rst
  tutorials/assets_pipeline/escn_exporter/mesh.rst
  tutorials/assets_pipeline/escn_exporter/physics.rst
  tutorials/assets_pipeline/escn_exporter/skeleton.rst
  tutorials/editor/index.rst
  tutorials/editor/project_manager.rst
  tutorials/editor/using_the_android_editor.rst
  tutorials/editor/using_the_xr_editor.rst
  tutorials/export/exporting_for_macos.rst
  tutorials/physics/troubleshooting_physics_issues.rst
  tutorials/rendering/index.rst
  tutorials/scripting/c_sharp/c_sharp_global_classes.rst
  tutorials/scripting/gdscript/gdscript_basics.rst
  tutorials/scripting/gdscript/static_typing.rst
  tutorials/shaders/shader_reference/canvas_item_shader.rst
  tutorials/shaders/shader_reference/shading_language.rst
Labels: merge:godot

#44 Merge commit godotengine/godot-docs@9f221dc
  about/release_policy.rst
  contributing/workflow/pr_workflow.rst
  tutorials/3d/img/spatial_material7.png
  tutorials/3d/img/spatial_material7.webp
  tutorials/3d/particles/properties.rst
  tutorials/3d/standard_material_3d.rst
  tutorials/animation/2d_skeletons.rst
  tutorials/animation/animation_tree.rst
  tutorials/audio/sync_with_audio.rst
  tutorials/best_practices/scenes_versus_scripts.rst
  tutorials/editor/using_the_web_editor.rst
  tutorials/export/exporting_for_windows.rst
  tutorials/inputs/controllers_gamepads_joysticks.rst
  tutorials/migrating/upgrading_to_godot_4.rst
  tutorials/scripting/gdscript/gdscript_styleguide.rst
  tutorials/scripting/gdscript/static_typing.rst
  tutorials/shaders/shader_reference/canvas_item_shader.rst
  tutorials/shaders/shader_reference/shader_preprocessor.rst
  tutorials/shaders/shader_reference/shading_language.rst
  tutorials/xr/a_better_xr_start_script.rst
Labels: merge:godot

#55 Remove refs to 3.6
  .github/workflows/build_offline_docs.yml
  README.md
  about/docs_changelog.rst
  about/release_policy.rst
  index.rst
  migrate.py
Labels: rebranding
